Hite.Web.SiteV2/Controllers/ChannelController.cs
/*******************************************************************  
 * Copyright (C) vancl.com
 * All rights reserved. 
 * 
 * Created By: VANCLOA\xingbaifang
 * Create Date:2011-08-17 16:34:26
 * Last Modified By:VANCLOA\xingbaifang
 * Last Modified Date:2011-08-17 16:34:26
 * Description: /Channel/xx.html和/hr.html用的
 * ********************************************************************/  
using System.Text;
using System.Collections.Generic;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Text.RegularExpressions;

using Hite.Mvc;
using Hite.Model;
using Hite.Services;
using Controleng.Common;
using Hite.Mvc.Filters;
using System.Resources;



namespace Hite.Web.Controllers.Site
{
    [SilenceHandleError]
    public class ChannelController : HiteController
    {
        #region == 人才招聘 ==
        /// <summary>
        /// 人才招聘Action
        /// /hr.html
        /// 自动跳到某一个栏目下（一般是未启用的类别）
        /// </summary>
        /// <returns></returns>
        
        public ActionResult Hr() {
            var siteInfo = HiteContext.Current.Site;
            int categoryId = 0;
            switch(siteInfo.IndexFileName){
                default:
                case IndexFileNameOfSite.WWW:
                    {
                        categoryId = siteInfo.Language == WebLanguage.zh_cn ? 287 : 728 ;
                    }
                    break;
                case IndexFileNameOfSite.Systematic:
                    categoryId = siteInfo.Language == WebLanguage.zh_cn ? 322 : 743;
                    break;
                case IndexFileNameOfSite.Hoisting:
                    categoryId = siteInfo.Language == WebLanguage.zh_cn ? 294 : 748;
                    break;
                case IndexFileNameOfSite.Electric:
                    categoryId = siteInfo.Language == WebLanguage.zh_cn ? 329 : 732;
                    break;
                case IndexFileNameOfSite.Energy:
                    categoryId = siteInfo.Language == WebLanguage.zh_cn ? 308 : 758;
                    break;
                case IndexFileNameOfSite.Mechatronics:
                    categoryId = siteInfo.Language == WebLanguage.zh_cn ? 315 : 753;
                    break;
                case IndexFileNameOfSite.Distribution:
                    categoryId = siteInfo.Language == WebLanguage.zh_cn ? 301 : 738;
                    break;
                case IndexFileNameOfSite.Hiscom:
                    categoryId = siteInfo.Language == WebLanguage.zh_cn ? 398 : 763;
                    break;
            }
            //当前节点
            var currentCategoryInfo = CategoryService.Get(categoryId);
            if (currentCategoryInfo.Id == 0)
            {
                return Content("Arguments Error!");
            }
            return LoadChannelShowPage(siteInfo, currentCategoryInfo);
        }
        #endregion

        #region == Channel Show ==
        public ActionResult Show()
        {
            /*
             总模板页需要以下变量
             * 1，根据Url获得根节点信息，因为左边需要导航信息
             * 2，根据Url获得所属类别，因为右边区域有个副导航
             */
            //Channel格式，必须为/Channel/(\d+).html
            //优先选择这样的格式
            var siteInfo = HiteContext.Current.Site;
            int categoryId = 0;
            string path = Goodspeed.Web.UrlHelper.Current.Path;
            string _urlCatName = Regex.Match(path, @"channel/(\w+)\.html", RegexOptions.IgnoreCase).Groups[1].Value;
            if (Regex.IsMatch(_urlCatName, @"\d+"))
            {
                //不是别名
                categoryId = Controleng.Common.Utils.StrToInt(_urlCatName, 0);
            }
            else
            {
                //是别名的情况
                categoryId = CategoryService.ListBySiteId(siteInfo.Id, true).FirstOrDefault(p => p.Alias == _urlCatName).Id;
            }
            //当前节点
            var currentCategoryInfo = CategoryService.Get(categoryId, true);
            if (currentCategoryInfo.Id == 0)
            {
                return Content("Arguments Error!");
            }
            return LoadChannelShowPage(siteInfo, currentCategoryInfo);
        }
        [NonAction]
        public ActionResult LoadChannelShowPage(SiteInfo currentSiteInfo,CategoryInfo catInfo) {
            //当前节点
            var currentCategoryInfo = catInfo;
            //根节点
            CategoryInfo rootCategoryInfo = currentCategoryInfo;
            //返回的模板HTML
            MvcHtmlString templateHtml = null;
            if (currentCategoryInfo != null && currentCategoryInfo.Id > 0)
            {

                //创建右边区域导航
                if (currentCategoryInfo.IsShowFirstChildNode)
                {
                    //如果显示一级子分类的第一个
                    var first = CategoryService.ListByParentId(currentCategoryInfo.Id, true).FirstOrDefault();
                    if (first != null && first.Id > 0)
                    {
                        currentCategoryInfo = first;
                    }
                }

                #region == 动态加载模板开始 ==
                //动态加载模板开始
                switch (currentCategoryInfo.TemplateType)
                {
                    case (int)TemplateType.ArticleListWithCategory:
                    case (int)TemplateType.ArticleList:
                    case (int)TemplateType.ArticleListWithTopOneImage:
                    case (int)TemplateType.ArticleListWithImage:
                        {
                            string viewName = ((TemplateType)Enum.Parse(typeof(TemplateType), currentCategoryInfo.TemplateType.ToString())).ToString();

                            //文章列表（头一条带有图片）
                            int pageIndex = CECRequest.GetQueryInt("page", 1);
                            int pageSize = 10;

                            var articleList = ArticleService.List(new SearchSetting() { 
                                PageIndex  = pageIndex,
                                PageSize = pageSize,
                                SiteId = currentSiteInfo.Id,
                                CategoryId = currentCategoryInfo.Id
                            },currentSiteInfo.Language);

                            ViewDataDictionary vdd = new ViewDataDictionary();
                            vdd.Add("PageIndex", pageIndex);
                            vdd.Add("PageSize", pageSize);
                            vdd.Add("CurrentCategoryInfo", currentCategoryInfo);
                            vdd.Add("Total", articleList.TotalItemCount);
                            vdd.Add("ArticleList", articleList);
                            vdd.Add("Language",currentSiteInfo.Language);

                            templateHtml = Partial(viewName, articleList, vdd);
                        }
                        break;
                    case (int)TemplateType.CategoryListWithOneColumn:
                        {
                            //根据当前ID获得一级子栏目
                            var categoryList = CategoryService.ListByParentId(currentCategoryInfo.Id, true);
                            //对每一个分类，添加几条文章
                            //分类中有个ArticleList的扩展属性
                            var rows = 5; //显示5条
                            foreach (var item in categoryList)
                            {
                                item.ArticleList = ArticleService.ListWithoutPage(currentSiteInfo.Id, item.Id, rows, currentSiteInfo.Language);
                            }
                            ViewDataDictionary vdd = new ViewDataDictionary();
                            vdd.Add("Language", currentSiteInfo.Language);
                            templateHtml = Partial(TemplateType.CategoryListWithOneColumn.ToString(), categoryList,vdd);
                        }
                        break;
                    case (int)TemplateType.CategoryListWithTwoColumn:
                        {
                            //根据当前ID获得一级子栏目
                            var categoryList = CategoryService.ListByParentId(currentCategoryInfo.Id, true) ;
                            templateHtml = Partial(TemplateType.CategoryListWithTwoColumn.ToString(), categoryList);
                        }
                        break;
                    case (int)TemplateType.JobList:
                        {
                            int pageIndex = CECRequest.GetQueryInt("page", 1);
                            int pageSize = 10;

                            var jobList = JobService.List(new SearchSetting() { 
                                SiteId = currentSiteInfo.Id,
                                PageIndex = pageIndex,
                                PageSize = pageSize
                            });
                            templateHtml = Partial(TemplateType.JobList.ToString(),jobList);
                        }
                        break;
                    case (int)TemplateType.AttachmentList: {
                        int pageIndex = CECRequest.GetQueryInt("page", 1);
                        int pageSize = 10;

                        var attachList = AttachmentService.List(new SearchSetting()
                        {
                            SiteId = currentSiteInfo.Id,
                            PageIndex = pageIndex,
                            PageSize = pageSize,
                            CategoryId = currentCategoryInfo.Id
                        });
                        templateHtml = Partial(TemplateType.AttachmentList.ToString(), attachList);
                    } break;
                    default:
                    case (int)TemplateType.ShowSingleCategoryInfo:
                        {
                            //显示一条类别详细信息（图片和描述）,不显示此类别下的文章
                            //如果此栏目默认显示自己子节点的第一条栏目，则取出子栏目的默认一条
                            //大部分是针对根节点来说的，有的时候根节点没有模板页，则点击根节点的时候，默认显示自己子节点的第一个栏目内容
                            templateHtml = Partial(TemplateType.ShowSingleCategoryInfo.ToString(), currentCategoryInfo);
                        }
                        break;
                        
                }

Hite.Web.SiteV2/Views/Shared/404.cshtml
@{
    ViewBag.Title = "你所访问的文件不存在";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section header{
    <style type="text/css">
        .wrapper{ background-color:#fff;padding:10px;}
        .area-left{float:left;width:120px; margin-left:175px;}
        .area-right{float:right;width:590px; margin-left:56px;}
        .area-right{width:590px;margin-left:56px;}
        .area-right h2{color:#333;font-size:16px;font-weight:bold;}
        .area-right h3{color:#666;}
        .area-right h3 strong{margin:0 6px;color:#a10000;font-weight:bold;}
        .blank0{clear:both;display:block;font-size:1px;visibility:hidden;height:0;line-height:0;}
        .blank5{clear:both;display:block;font-size:1px;overflow:hidden;height:5px;}
        .blank8{clear:both;display:block;font-size:1px;overflow:hidden;height:8px;}
        .blank10{clear:both;display:block;font-size:1px;overflow:hidden;height:10px;}
        .blank12{clear:both;display:block;font-size:1px;overflow:hidden;height:12px;}
        .blank15{clear:both;display:block;font-size:1px;overflow:hidden;height:15px;}
        .blank20{clear:both;display:block;font-size:1px;overflow:hidden;height:20px;}
        .blank25{clear:both;display:block;font-size:1px;overflow:hidden;height:25px;}
        .btn-back{width:85px;height:26px;margin-left:10px;padding-left:18px;background:url(/images/btn-home-bg.gif) no-repeat;color:#fff;border:0;cursor:pointer;}
        .btn-area span,.btn-area input{line-height:26px;float:left;display:inline;}
        .btn-area span{color:#666;}
    </style>
    <script type="text/javascript">
        function lazyBackHome() {
            var sec = $("#sec").text();
            $("#sec").text(--sec);
            if (sec > 0)
                setTimeout("lazyBackHome();", 1000);
            else
                window.location.href = "/";
        }
    </script>
}
<div class="wrapper">
    <div class="area-left">
        <img src="/images/404.gif" alt="" /></div>
    <div class="area-right">
        <span class="blank15"></span><span class="blank15"></span>
        <h2>
            对不起，您要访问的页面暂时没有找到！</h2>
        <span class="blank8"></span>
        <h3>
            将在<strong id="sec">10</strong>秒后自动转入首页。</h3>
        <span class="blank20"></span>
        <div class="btn-area">
            <span>您也可以：</span><input type="button" value="返回首页" class="btn-back" onclick="window.location.href='/'" />
        </div>
    </div>
    <div class="clear"></div>
</div>
@section footer{
    <script type="text/javascript">
        $(document).ready(function () {
            lazyBackHome();
        });
    </script>
}

Hite.Web.SiteV2/Views/Shared/_AccountLayout.cshtml
@{
    Layout = "_Layout.cshtml";
}
@section header{
    <style type="text/css">
        .usr{background-color:#fff;color:#000;}
        .usr h2{padding:10px; font-weight:bold; font-size:14px;border-bottom:1px solid #CCCCCC; margin-bottom:10px;}
        .usr-nav-block{border-bottom:1px solid #CCCCCC; float:left; font-size:14px; padding-left:10px; position:relative;width:960px;}
        .usr-nav-block li{float:left; margin-left:5px;}
        .usr-nav-block a{ background-color:#E5EEF7; border:1px solid #CCCCCC;color:#484853; float:left; letter-spacing:1px;padding:5px 10px; position:relative;top:1px;}
        .usr-nav-block a.current{ background-color:white; border-bottom:1px solid white; cursor:default; font-weight:bold; letter-spacing:0;padding:5px 10px;}
         .text{border:1px solid #BBBBBB; height:16px;padding:4px 3px; width:200px;}
        .usr-content{padding:10px;}
        
        .msg{color:Red; padding:10px; display:block;font-weight:bold;border:1px red dotted; margin-bottom:10px;}
    </style>
    <script src="/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    @RenderSection("header", false)
}
<div class="usr clearfix">
    <h2>@(Hite.Mvc.LanguageResourceHelper.GetString("user-center-text",PageData["SiteInfo"].Language))</h2>
    @RenderBody()
</div>

@section footer{
    @RenderSection("footer", false)
}

Hite.Web.SiteV2/Views/Shared/_ChannelLayout.cshtml
@{
    Layout = "_Layout.cshtml";
    if (ViewBag.RootCategoryInfo == null)
    {
        ViewBag.RootCategoryInfo = new Hite.Model.CategoryInfo();
    }
}
@section Header{
    <script type="text/javascript">
        _GLOBAL.menuRootId = @ViewBag.RootCategoryInfo.Id;
    </script>
    @RenderSection("header", false)
}
<div id="cat-banner">
    <img alt="@ViewBag.RootCategoryInfo.Name" src="@ViewBag.RootCategoryInfo.BannerAdImageUrl" />
</div>
<div class="blankb">
</div>
<div class="section-wrapper clearfix">
    <div class="section-column">
        <h4>
            @(ViewBag.RootCategoryInfo.Name)</h4>
        <div class="cat-sub-list clearfix">
            @{Html.RenderAction("SubCategoryListForChannelPage", "Channel", new { rootId = ViewBag.RootCategoryInfo.Id, selectedId = ViewBag.CurrentCategoryInfo.Id, language = PageData["SiteInfo"].Language });}
        </div>
        <div class="clear">
        </div>
        <div class="site-hp">
            <ul>
                @if (PageData["SiteInfo"].Language == Hite.Model.WebLanguage.zh_cn)
                {
                    <text><li><a href="/feedback.html">
                        <img src="/images/feedbackicon.gif" alt="在线反馈" width="159" height="46" /></a></li>
                    <li><a href="/hr.html">
                        <img src="/images/jobsicon.gif" alt="人才招聘专区" width="159" height="46" /></a></li>
                    <li><a href="/contactus.html">
                        <img src="/images/contactusicon.gif" alt="联系我们" width="159" height="46" /></a></li></text>
                }
                else
                { 
                    <text><li><a href="/en/feedback.html">
                        <img src="/images/en_feedbackicon.gif" width="159" height="46" /></a></li>
                    <li><a href="/en/hr.html">
                        <img src="/images/en_jobsicon.gif" width="159" height="46" /></a></li>
                    <li><a href="/en/contactus.html">
                        <img src="/images/en_contactusicon.gif" width="159" height="46" /></a></li></text>
                }
            </ul>
        </div>
    </div>
    <div class="section-content">
        <div class="page-round-top">
        </div>
        <div class="page-sub-nav">
            <h5>
                @{Html.RenderAction("RenderSubNavForChannelPage", "Channel", new { siteId = ViewBag.RootCategoryInfo.SiteId, catId = ViewBag.CurrentCategoryInfo.Id, customTitle = ViewBag.SubNavCustomTitle, language = PageData["SiteInfo"].Language });}
            </h5>
        </div>
        <div class="page-content">
            @RenderBody()
        </div>
        <div class="page-round-bottom">
        </div>
    </div>
    <div class="clear">
    </div>
</div>
@section footer{
    @RenderSection("footer", false)
}

Hite.Web.SiteV2/Views/Shared/_Layout.cshtml
@{
    var siteInfo = PageData["SiteInfo"];
    }
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - @siteInfo.WebTitle</title>
    <link rel="shortcut icon" href="http://www.hite.com.cn/favicon.ico" type="image/x-icon" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=7" />
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
    <meta name="author" content="兴百放,xbf321(at)gmail.com" />
    <meta name="Keywords" content="@(ViewBag.Keywords != null ? ViewBag.Keywords : siteInfo.WebKeywords)" />
    <meta name="Description" content="@(ViewBag.Description != null ? ViewBag.Description : siteInfo.WebDesc)" />
    <link type="text/css" rel="stylesheet" href="/static/css?href=styles/global.css,styles/@(siteInfo.IndexFileName.ToString().ToLower()).css,styles/jquery.ddsmoothmenu.css,styles/jquery.xDialog.css,20141010.css"/>
    @if (siteInfo.Language == Hite.Model.WebLanguage.en)
    { 
    <link rel="alternate" hreflang="cn" href="http://www.hite.com.cn" />
    <link type="text/css" rel="stylesheet" href="/styles/hack/@(siteInfo.IndexFileName.ToString().ToLower()).css"/>
    }
    else { 
    <link rel="alternate" hreflang="en" href="http://www.hite.com.cn/en" />
    }
    <script src="/static/js?src=scripts/jquery-1.4.4.min.js,scripts/jquery.jcarousellite_1.0.1.js,scripts/jquery.ddsmoothmenu.js,scripts/jquery.xDialog.js,scripts/jquery.slide.js,/scripts/jquery.tmpl.min.js,/scripts/jquery.cookie.js,201304082151.js"></script>
    <script type="text/javascript">
        var _GLOBAL = { menuRootId: 0, passportServer: "@(System.Configuration.ConfigurationManager.AppSettings["PassportUrl"])@(siteInfo.Language == Hite.Model.WebLanguage.en ? "/en" : "")",login: function () { var _h = window.location.href; if (_h.indexOf('/accounts/login') !==-1 || _h.indexOf('/accounts/register') !== -1) { _h = ''; } window.location.href = this.passportServer + '/accounts/login?ReturnUrl=' + encodeURIComponent(_h);},register: function () { var _h = window.location.href;if (_h.indexOf('/accounts/login') !==-1 || _h.indexOf('/accounts/register') !== -1) { _h = ''; } window.location.href = this.passportServer+'/accounts/register?ReturnUrl='+encodeURIComponent(_h); },logout:function(){window.location.href = this.passportServer + '/accounts/logout?ReturnUrl='+encodeURIComponent(window.location.href);}};
    </script>@RenderSection("header", false)
</head>
<body>
    <div id="header" class="clearfix">
        <div class="logo">
            <a href="/@(siteInfo.Language == Hite.Model.WebLanguage.en ? "en" : "")" title="@siteInfo.Name">
                <img src="@siteInfo.Logo" alt="@siteInfo.Name" /></a>
        </div>
        <div class="link">@Html.Raw(Hite.Mvc.LanguageResourceHelper.GetString("site-top-nav-text", siteInfo.Language))@{Html.RenderPartial("_LoginUserControl", new { Language = @siteInfo.Language });}
        </div>
    </div>
    <div id="nav" class="ddsmoothmenu">
        <ul>
            <li class="l">&nbsp;</li>
            @{Html.RenderAction("CategoryListForHeader", "Home", new { siteId = siteInfo.Id });}
            <li class="search">
                <input type="text" class="search-key" name="txtHeaderSearchKey" id="txtHeaderSearchKey" value="@Request["q"]" />
                <input type="button" class="search-button" id="btnHeaderSearch" alt="@Hite.Mvc.LanguageResourceHelper.GetString("search-text", siteInfo.Language)" />
            </li>
            <li class="r"></li>
        </ul>
    </div>
    <div class="blankb">
    </div>
    <div id="main">
        @RenderBody()
    </div>
    <div id="footer">
        @Html.Raw(Hite.Mvc.LanguageResourceHelper.GetString("footer-text", siteInfo.Language))
    </div>
<div style="width:980px;margin:0 auto;text-align:center;"><script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F12bfcbe81fca32418c806918642a68e0' type='text/javascript'%3E%3C/script%3E"));
</script></div>
    <script type="text/javascript">
        ddsmoothmenu.init({
            mainmenuid: "nav", //menu DIV id
            orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
            classname: 'ddsmoothmenu', //class added to menu's outer DIV
            contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
        })
        jQuery.fn.extend({
            pressEnter: function (fun) {
                this.keypress(function (e) {
                    if (e.which == "13") {
                        fun.call(this, arguments);
                        return this;
                    }
                });
            }
        });
        $(document).ready(function () {
            $("#nav > ul > li").each(function (index) {
                var aObj = $(this).find("a").first();
                if (aObj.length > 0) {
                    if (_GLOBAL.menuRootId == aObj.attr('id')) {
                        $(this).addClass("current").siblings().removeClass("current");
                    }
                }
            });
            $("#txtHeaderSearchKey").focus();
            $('#btnHeaderSearch').click(function () {
                var keyObj = $('#txtHeaderSearchKey');
                if (keyObj.val() == "") { keyObj.focus(); return false; } else {
                    window.location.href = '/search.html?q=' + encodeURIComponent(keyObj.val());
                }
            });
        });        
    </script>@RenderSection("footer", false)
    <script type="text/javascript">
        var referrer = window.encodeURIComponent(document.referrer);
        var url = "<scr" + "ipt type=\"text/javascript\" src=\"/static/statistics?siteid=@(siteInfo.Id)&referrer=" + referrer + "\"></scr" + "ipt\>";
        document.write(url);
    </script>

    @Html.Raw(siteInfo.ThirdCode)
</body>
</html>

Hite.Web.SiteV2/Views/Shared/_LoginUserControl.cshtml
@if (Request.Url.Host.IndexOf("hite.com.cn") > 0)
{
    //说明在hite.com.cn域下
    if (Request.IsAuthenticated){<text><br /><b>@HttpContext.Current.User.Identity.Name</b>！@Html.Raw(Hite.Mvc.LanguageResourceHelper.GetString("logged-in-bar-text", Model.Language))</text>}else{<text>@Html.Raw(Hite.Mvc.LanguageResourceHelper.GetString("not-logged-in-bar-text", Model.Language))</text>}
}
else
{
    //判断Cookie
    <text> 
    <span id="login-info">
        <script type="text/javascript">
            (function () {var d = document.domain, d = d.match(/([\-\w]+\.(?:com\.cn|com)+)/i)[0];$.getScript(_GLOBAL.passportServer + "/static/loginapi?" + Math.random(), function () {for (var i in userCookie) {$.cookie(i, userCookie[i], { domain: d, path: '/' })}var _ht_ = userCookie._ht_, _hr_ = userCookie._hr_, _usr_ = userCookie.usr, _nk_ = userCookie.username, o = !!(_hr_ && _ht_ && _usr_ && _nk_), k = '';if (o) { k = '<br /><b>' + _nk_ + '</b>！@Html.Raw(Hite.Mvc.LanguageResourceHelper.GetString("logged-in-bar-text", Model.Language))'; } else { k = '@(Html.Raw(Hite.Mvc.LanguageResourceHelper.GetString("not-logged-in-bar-text", Model.Language)))'; } $("#login-info").html(k);});})();
        </script>
    </span>
    </text>
}

Hite.Web.SiteV2/Views/Shared/_NavForAccount.cshtml
<div class="usr-nav-block">
    <ul>
        <li><a href="modify" class="@(Model.ToLower() == "modify" ? "current" : string.Empty)">@Hite.Mvc.LanguageResourceHelper.GetString("modify-text", (Hite.Model.WebLanguage)ViewData["Language"])</a></li>
        <li><a href="setpwd" class="@(Model.ToLower() == "setpwd" ? "current" : string.Empty)">@Hite.Mvc.LanguageResourceHelper.GetString("chanage-pwd-text", (Hite.Model.WebLanguage)ViewData["Language"])</a></li>
        <li><a href="forumapply" class="@(Model.ToLower() == "forumapply" ? "current" : string.Empty)">申请论坛用户</a></li>
        @*<li>@Html.ActionLink("修改信息", "modify", new { }, new { @class = (Model.ToLower() == "modify" ? "current" : string.Empty) })</li>
        <li>@Html.ActionLink("修改密码", "setpwd", new { }, new { @class = (Model.ToLower() == "setpwd" ? "current" : string.Empty) })</li>
        <li>@Html.ActionLink("申请论坛用户", "forumapply", new { }, new { @class = (Model.ToLower() == "forumapply" ? "current" : string.Empty) })</li>*@
    </ul>
</div>
<div class="clear"></div>